---
title: "Survival Models in Stan"
---

## Motivating Example

Surivival analysis is an informative way to examine "time to event" data generating structures.

From <https://rstudio-pubs-static.s3.amazonaws.com/435225_07b4ab5afa824342a4680c9fb2de6098.html>

## The Set-up

```{r}
library(tidyverse)
library(rstan)
library(survival)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

<https://stats.stackexchange.com/questions/135124/how-to-create-a-toy-survival-time-to-event-data-with-right-censoring>
```{r}
# N = sample size    
# lambda = scale parameter in h0()
# rho = shape parameter in h0()
# beta = fixed effect parameter
# rateC = rate parameter of the exponential distribution of C

simul_weibull_survival <- function(N = 100, 
                                   lambda = 0.001, 
                                   rho = 1, 
                                   covariate_type = c("bernoullii",
                                                      "continuous"),
                                   beta, 
                                   rateC = 0.001)
{
  # covariate --> N Bernoulli trials
  type <- match.arg(arg = covariate_type)
  
  x <- switch(type,
         bernoullii = sample(x=c(0, 1), size=N, replace=TRUE, prob=c(0.5, 0.5)),
         continuous = rnorm(N, 1 , 1)
         )

  # Weibull latent event times
  v <- runif(n=N)
  Tlat <- (- log(v) / (lambda * exp(x * beta)))^(1 / rho)

  # censoring times
  C <- rexp(n=N, rate=rateC)

  # follow-up times and event indicators
  time <- pmin(Tlat, C)
  status <- as.integer(Tlat <= C)

  # data set
  data.frame(id=1:N,
             time=round(time,0),
             status=status,
             x=as.factor(x))
}

dat <- simul_weibull_survival(beta = .5, covariate_type = "bernoullii")
dat
mean(dat$status)
glimpse(dat)
fit <- survfit(Surv(status, time)~1, dat = dat)
glimpse(as.data.frame(leukemia))
summary(dat)
summary(fit)
```

```{r}

x <- 
beta <- c(4, 5, 3)
t(beta)
```


## MLE Style

```{r}
library(survival)

mle_fit <- survfit(Surv(time, event) ~ x1 + x2)
summary(mle_fit)
```

## Stan Model

```{r comment=""}
writeLines(readLines("stan_survival_model.stan"))
```

Now compile the model

```{r}
survival_model <- stan_model("stan_survival_model.stan")
```

## Stan Data

```{r}
stan_data <-
    list(
        ## Number of event individuals
        Nobs = sum(leukemia$status == 1),
        ## Number of censored individuals
        Ncen = sum(leukemia$status == 0),
        ## Number of covariates
        M_bg = 1,
        ## Times for event individuals
        yobs = leukemia$time[leukemia$status == 1],
        ## Times for censored individuals
        ycen = leukemia$time[leukemia$status == 0],
        ## Covariates for event individuals as a matrix
        Xobs_bg = matrix(as.numeric(leukemia$x == "Maintained")[leukemia$status == 1]),
        ## Covariates for censored individuals as a matrix
        Xcen_bg = matrix(as.numeric(leukemia$x == "Maintained")[leukemia$status == 0])
        )
```


## Fit the Model

```{r}
survival_fit <-  sampling(survival_model, 
                          stan_data, 
                          cores = 3, 
                          iter = 2000, 
                          seed = 1234,
                          chains = 3, refresh=0, 
                          control = list(adapt_delta = .95,
                                         max_treedepth = 15))

```


## Model Fit Diagnostics

```{r}
diagnostics <- new.env()

source("stan_utilities.R", local = diagnostics)

diagnostics$check_all_diagnostics(survival_fit)

```

```{r}
traceplot(survival_fit, par = c("alpha","mu","beta_bg"))
```

```{r}
bayesplot::mcmc_areas(as.matrix(survival_fit), pars = c("alpha","mu","beta_bg[1]"), prob = 0.95)
```

## Inferences



